# Site settings
title: "OCTAS.SPACE"
description: ""
url: ""
author: "OCTAVR"
  name: "OCTAVR"
  email: "necsta@gmail.com"
  url: "http://OCTAS.SPACE"

# Build settings
baseurl: /OCTAS.SPACE.WEB/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: _site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
