# Site settings
title: OCTAS.SPACE
description: "OCTAS.SPACE"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "OCTAVR"
  email: "necsta@hmail.com"
  url: "http://OCTAS.SPACE"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./OCTAS.SPACE.WEB
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
